/**
 * Regenerates `docs/extensions.md` from `docs/extensions.tpl.md`.
 *
 * The guide's prose lives in the template; its code blocks do not. A line of
 * the form
 *
 * ```text
 * @@ <path> :: <first line> :: <last line> [:: <language>]
 * ```
 *
 * is replaced by the slice of `examples/extension-template/<path>` running from
 * the line equal to `<first line>` through the next line equal to `<last line>`,
 * dedented, fenced, and preceded by a comment naming the source. Anchors are
 * compared with surrounding whitespace trimmed.
 *
 * Run with `bun scripts/extensions.ts`. `test/extensions-guide.test.ts` proves
 * the committed guide still matches the template, whether or not it was
 * generated by this script.
 */
import { readFileSync, writeFileSync } from "node:fs"

const TEMPLATE_DIR = "examples/extension-template"
const INPUT = "docs/extensions.tpl.md"
const OUTPUT = "docs/extensions.md"

const fail = (message: string): never => {
  console.error(message)
  process.exit(1)
}

/** The common indentation of the non-empty lines of a block. */
const dedent = (lines: ReadonlyArray<string>): string => {
  const widths = lines
    .filter((line) => line.trim() !== "")
    .map((line) => line.length - line.trimStart().length)
  const common = widths.length === 0 ? 0 : Math.min(...widths)
  return lines.map((line) => line.slice(common)).join("\n")
}

const indentOf = (line: string): number => line.length - line.trimStart().length

/**
 * The slice from the first line equal to `first` through the next line equal to
 * `last` **at the same indentation**, which is what makes a closing brace or
 * parenthesis an unambiguous anchor: the nested ones are further in.
 */
const slice = (path: string, first: string, last: string): string => {
  const lines = readFileSync(`${TEMPLATE_DIR}/${path}`, "utf8").split("\n")
  const start = lines.findIndex((line) => line.trim() === first.trim())
  if (start === -1) fail(`${path}: no line equal to ${JSON.stringify(first)}`)
  const indent = indentOf(lines[start] ?? "")
  const rest = lines.slice(start)
  // An end anchor written with leading whitespace means that exact line: the
  // escape hatch for a block that closes further in than it opened.
  const exact = last !== last.trimStart()
  const aligned = exact
    ? rest.findIndex((line, index) => index > 0 && line === last)
    : rest.findIndex((line, index) =>
      line.trim() === last.trim() && (index === 0 || indentOf(line) === indent)
    )
  // A closing brace or parenthesis is only unambiguous at the block's own
  // indentation; an anchor that is a continuation line (`| RunError`) is
  // indented further and matches on text alone.
  const offset = aligned === -1 && !exact
    ? rest.findIndex((line) => line.trim() === last.trim())
    : aligned
  if (offset === -1) {
    fail(`${path}: no line equal to ${JSON.stringify(last)} after ${JSON.stringify(first)}`)
  }
  return dedent(lines.slice(start, start + offset + 1))
}

const expand = (line: string): string => {
  // Fields are separated by `::`; trailing whitespace and one leading space go,
  // any further leading whitespace is meaningful (see `slice`).
  const parts = line.slice(2).split("::").map((part) => part.replace(/^ /, "").trimEnd())
  const [path, first, last, lang = "ts"] = parts
  if (path === undefined || first === undefined || last === undefined) {
    return fail(`malformed directive: ${line}`)
  }
  return [
    `<!-- from: ${TEMPLATE_DIR}/${path} -->`,
    "",
    `\`\`\`${lang}`,
    slice(path, first, last),
    "```"
  ].join("\n")
}

const source = readFileSync(INPUT, "utf8")
const output = source
  .split("\n")
  .map((line) => (line.startsWith("@@") ? expand(line) : line))
  .join("\n")

writeFileSync(OUTPUT, output)
console.error(`${OUTPUT}: ${output.length} characters`)
